version: '3.4'
services:
    api:
        build:
            context: .
            target: base
        container_name: meal-planner_api
        image: meal-planner_api
        command: npm start
        ports:
            - '8080:8080'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=dev
            - CLIENT_ORIGIN=*
            - MONGODB_URI=mongodb+srv://dbUser:dbUserPassword@cluster0-iinzg.mongodb.net/test?retryWrites=true&w=majority
        # depends_on:
        #     - database

    # database:
    #     image: mongo
    #     container_name: mongo_db
    #     ports:
    #         - '27017:27017'
    #     volumes:
    #         - data:/data/db
    #     command: mongod

    # db:
    #     image: postgres
    #     container_name: postgres
    #     ports:
    #         - '5432:5432'
    #     volumes:
    #         - data:/data/postgres
volumes:
    data:
