version: '3.4'
services:
  api:
    build:
      context: .
      target: base
    container_name: journal_api
    image: journal_api
    command: npm start
    ports:
    - '8080:8080'
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    environment:
    - NODE_ENV=dev
