version: '3.4'
services:
  api:
    build:
      context: .
      target: base
    container_name: journal_api
    image: journal_api
    command: npm start
    ports:
    - '8080:8080'
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    environment:
    - NODE_ENV=dev
    depends_on:
    - database

  database:
    image: mongo
    container_name: mongo_db
    ports:
    - "27017:27017"
    volumes:
    - data:/data/db
    command: mongod

volumes:
    data:
